#This compose file is for bringing up shared containers.
#Any container, network or volume that is going to be shared with every container on the host should be defined here.
version: '3.5'
networks:
  mahara-net:
    name: mahara-net

services:
  mail:
    image: mailhog/mailhog
    tty: true
    ports:
      - 8025:8025
    networks:
      - mahara-net

  nginx:
    image: nginx:latest
    volumes:
      - ./proxy/etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${MAHARA_DOCKER_PORT}:80
    networks:
      - mahara-net